apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-backend
  template:
    metadata:
      labels:
        app: guestbook-backend
    spec:
      containers:
        - name: backend
          image: localhost:5000/guestbook-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/guestbook"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: guestbook-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

